services:
  garnet-server:
    image: garnet-server
    hostname: redis.local
    command: ["GarnetServer", "--bind", "0.0.0.0"]
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  e2etests:
    image: e2etests:latest
    depends_on:
      garnet-server:
        condition: service_healthy
