{-# LANGUAGE OverloadedStrings #-}

module Database.Redis.Cluster.Commands.Generated
  ( generatedSourceRepo
  , generatedSourceRef
  , generatedSourceCommit
  , generatedSourceAggregateSha256
  , generatedCommandPayloadSha256
  , generatedCommandSpecs
  , generatedCommandSpecCount
  ) where

import           Data.ByteString                       (ByteString)
import           Database.Redis.Cluster.Commands.Types

generatedSourceRepo :: ByteString
generatedSourceRepo = "https://github.com/redis/redis"

generatedSourceRef :: ByteString
generatedSourceRef = "7.2"

generatedSourceCommit :: ByteString
generatedSourceCommit = "335554f18caf7bbf6b0ac2b3548133d750f00a1b"

generatedSourceAggregateSha256 :: ByteString
generatedSourceAggregateSha256 = "2f812557f27d57df525c72d3ebfe1dd4a16d1e6b47a5584d0cf83f45474b8dc2"

generatedCommandPayloadSha256 :: ByteString
generatedCommandPayloadSha256 = "bc0eed733a9ed5943e7091f9cdc0df58f9e014e00f39f1d88ebd9dbd31cf07e4"

generatedCommandSpecs :: [GeneratedCommandSpec]
generatedCommandSpecs =
  [ GeneratedCommandSpec "ACL" (-2) []
  , GeneratedCommandSpec "ADDSLOTS" (-3) []
  , GeneratedCommandSpec "ADDSLOTSRANGE" (-4) []
  , GeneratedCommandSpec "APPEND" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ASKING" (1) []
  , GeneratedCommandSpec "AUTH" (-2) []
  , GeneratedCommandSpec "BGREWRITEAOF" (1) []
  , GeneratedCommandSpec "BGSAVE" (-1) []
  , GeneratedCommandSpec "BITCOUNT" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BITFIELD" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BITFIELD_RO" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BITOP" (-4) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (3)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "BITPOS" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BLMOVE" (6) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BLMPOP" (-5) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "BLPOP" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-2) (1) (0))]
  , GeneratedCommandSpec "BRPOP" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-2) (1) (0))]
  , GeneratedCommandSpec "BRPOPLPUSH" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "BUMPEPOCH" (2) []
  , GeneratedCommandSpec "BZMPOP" (-5) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "BZPOPMAX" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-2) (1) (0))]
  , GeneratedCommandSpec "BZPOPMIN" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-2) (1) (0))]
  , GeneratedCommandSpec "CACHING" (3) []
  , GeneratedCommandSpec "CAT" (-2) []
  , GeneratedCommandSpec "CHANNELS" (-2) []
  , GeneratedCommandSpec "CKQUORUM" (3) []
  , GeneratedCommandSpec "CLIENT" (-2) []
  , GeneratedCommandSpec "CLUSTER" (-2) []
  , GeneratedCommandSpec "COMMAND" (-1) []
  , GeneratedCommandSpec "CONFIG" (-2) []
  , GeneratedCommandSpec "CONFIG" (-4) []
  , GeneratedCommandSpec "CONSUMERS" (4) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "COPY" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "COUNT" (2) []
  , GeneratedCommandSpec "COUNT-FAILURE-REPORTS" (3) []
  , GeneratedCommandSpec "COUNTKEYSINSLOT" (3) []
  , GeneratedCommandSpec "CREATE" (-5) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "CREATECONSUMER" (5) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DBSIZE" (1) []
  , GeneratedCommandSpec "DEBUG" (-2) []
  , GeneratedCommandSpec "DEBUG" (3) []
  , GeneratedCommandSpec "DEBUG" (-2) []
  , GeneratedCommandSpec "DECR" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DECRBY" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DEL" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "DELCONSUMER" (5) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DELETE" (3) []
  , GeneratedCommandSpec "DELSLOTS" (-3) []
  , GeneratedCommandSpec "DELSLOTSRANGE" (-4) []
  , GeneratedCommandSpec "DELUSER" (-3) []
  , GeneratedCommandSpec "DESTROY" (4) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DISCARD" (1) []
  , GeneratedCommandSpec "DOCS" (-2) []
  , GeneratedCommandSpec "DOCTOR" (2) []
  , GeneratedCommandSpec "DOCTOR" (2) []
  , GeneratedCommandSpec "DRYRUN" (-4) []
  , GeneratedCommandSpec "DUMP" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "DUMP" (2) []
  , GeneratedCommandSpec "ECHO" (2) []
  , GeneratedCommandSpec "ENCODING" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "EVAL" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "EVAL_RO" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "EVALSHA" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "EVALSHA_RO" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "EXEC" (1) []
  , GeneratedCommandSpec "EXISTS" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "EXISTS" (-3) []
  , GeneratedCommandSpec "EXPIRE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "EXPIREAT" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "EXPIRETIME" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "FAILOVER" (-2) []
  , GeneratedCommandSpec "FAILOVER" (-1) []
  , GeneratedCommandSpec "FAILOVER" (3) []
  , GeneratedCommandSpec "FCALL" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "FCALL_RO" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "FLUSH" (-2) []
  , GeneratedCommandSpec "FLUSH" (-2) []
  , GeneratedCommandSpec "FLUSHALL" (-1) []
  , GeneratedCommandSpec "FLUSHCONFIG" (2) []
  , GeneratedCommandSpec "FLUSHDB" (-1) []
  , GeneratedCommandSpec "FLUSHSLOTS" (2) []
  , GeneratedCommandSpec "FORGET" (3) []
  , GeneratedCommandSpec "FREQ" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "FUNCTION" (-2) []
  , GeneratedCommandSpec "GENPASS" (-2) []
  , GeneratedCommandSpec "GEOADD" (-5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEODIST" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEOHASH" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEOPOS" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEORADIUS" (-6) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginKeyword "STORE" (6)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginKeyword "STOREDIST" (6)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEORADIUS_RO" (-6) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEORADIUSBYMEMBER" (-5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginKeyword "STORE" (5)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginKeyword "STOREDIST" (5)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEORADIUSBYMEMBER_RO" (-5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEOSEARCH" (-7) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GEOSEARCHSTORE" (-8) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GET" (-3) []
  , GeneratedCommandSpec "GET" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GET" (-2) []
  , GeneratedCommandSpec "GET-MASTER-ADDR-BY-NAME" (3) []
  , GeneratedCommandSpec "GETBIT" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GETDEL" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GETEX" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GETKEYS" (-3) []
  , GeneratedCommandSpec "GETKEYSANDFLAGS" (-3) []
  , GeneratedCommandSpec "GETKEYSINSLOT" (4) []
  , GeneratedCommandSpec "GETNAME" (2) []
  , GeneratedCommandSpec "GETRANGE" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GETREDIR" (2) []
  , GeneratedCommandSpec "GETSET" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "GETUSER" (3) []
  , GeneratedCommandSpec "GRAPH" (3) []
  , GeneratedCommandSpec "GROUPS" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HDEL" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HELLO" (-1) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HELP" (2) []
  , GeneratedCommandSpec "HEXISTS" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HGET" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HGETALL" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HINCRBY" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HINCRBYFLOAT" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HISTOGRAM" (-2) []
  , GeneratedCommandSpec "HISTORY" (3) []
  , GeneratedCommandSpec "HKEYS" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HLEN" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HMGET" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HMSET" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HRANDFIELD" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HSCAN" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HSET" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HSETNX" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HSTRLEN" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "HVALS" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ID" (2) []
  , GeneratedCommandSpec "IDLETIME" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "INCR" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "INCRBY" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "INCRBYFLOAT" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "INFO" (2) []
  , GeneratedCommandSpec "INFO" (2) []
  , GeneratedCommandSpec "INFO" (-2) []
  , GeneratedCommandSpec "INFO" (-1) []
  , GeneratedCommandSpec "INFO-CACHE" (-3) []
  , GeneratedCommandSpec "IS-MASTER-DOWN-BY-ADDR" (6) []
  , GeneratedCommandSpec "KEYS" (2) []
  , GeneratedCommandSpec "KEYSLOT" (3) []
  , GeneratedCommandSpec "KILL" (-3) []
  , GeneratedCommandSpec "KILL" (2) []
  , GeneratedCommandSpec "KILL" (2) []
  , GeneratedCommandSpec "LASTSAVE" (1) []
  , GeneratedCommandSpec "LATENCY" (-2) []
  , GeneratedCommandSpec "LATEST" (2) []
  , GeneratedCommandSpec "LCS" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (1) (1) (0))]
  , GeneratedCommandSpec "LEN" (2) []
  , GeneratedCommandSpec "LINDEX" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LINKS" (2) []
  , GeneratedCommandSpec "LINSERT" (5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LIST" (2) []
  , GeneratedCommandSpec "LIST" (-2) []
  , GeneratedCommandSpec "LIST" (-2) []
  , GeneratedCommandSpec "LIST" (-2) []
  , GeneratedCommandSpec "LIST" (2) []
  , GeneratedCommandSpec "LLEN" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LMOVE" (5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LMPOP" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "LOAD" (2) []
  , GeneratedCommandSpec "LOAD" (-3) []
  , GeneratedCommandSpec "LOAD" (-3) []
  , GeneratedCommandSpec "LOAD" (3) []
  , GeneratedCommandSpec "LOADEX" (-3) []
  , GeneratedCommandSpec "LOG" (-2) []
  , GeneratedCommandSpec "LOLWUT" (-1) []
  , GeneratedCommandSpec "LPOP" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LPOS" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LPUSH" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LPUSHX" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LRANGE" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LREM" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LSET" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "LTRIM" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "MALLOC-STATS" (2) []
  , GeneratedCommandSpec "MASTER" (3) []
  , GeneratedCommandSpec "MASTERS" (2) []
  , GeneratedCommandSpec "MEET" (-4) []
  , GeneratedCommandSpec "MEMORY" (-2) []
  , GeneratedCommandSpec "MGET" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "MIGRATE" (-6) [GeneratedKeySpec (BeginIndex (3)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginKeyword "KEYS" (-2)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "MODULE" (-2) []
  , GeneratedCommandSpec "MONITOR" (1) []
  , GeneratedCommandSpec "MONITOR" (6) []
  , GeneratedCommandSpec "MOVE" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "MSET" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (2) (0))]
  , GeneratedCommandSpec "MSETNX" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (2) (0))]
  , GeneratedCommandSpec "MULTI" (1) []
  , GeneratedCommandSpec "MYID" (2) []
  , GeneratedCommandSpec "MYID" (2) []
  , GeneratedCommandSpec "MYSHARDID" (2) []
  , GeneratedCommandSpec "NO-EVICT" (3) []
  , GeneratedCommandSpec "NO-TOUCH" (3) []
  , GeneratedCommandSpec "NODES" (2) []
  , GeneratedCommandSpec "NUMPAT" (2) []
  , GeneratedCommandSpec "NUMSUB" (-2) []
  , GeneratedCommandSpec "OBJECT" (-2) []
  , GeneratedCommandSpec "PAUSE" (-3) []
  , GeneratedCommandSpec "PENDING-SCRIPTS" (2) []
  , GeneratedCommandSpec "PERSIST" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PEXPIRE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PEXPIREAT" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PEXPIRETIME" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PFADD" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PFCOUNT" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "PFDEBUG" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PFMERGE" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "PFSELFTEST" (1) []
  , GeneratedCommandSpec "PING" (-1) []
  , GeneratedCommandSpec "PSETEX" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PSUBSCRIBE" (-2) []
  , GeneratedCommandSpec "PSYNC" (-3) []
  , GeneratedCommandSpec "PTTL" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "PUBLISH" (3) []
  , GeneratedCommandSpec "PUBSUB" (-2) []
  , GeneratedCommandSpec "PUNSUBSCRIBE" (-1) []
  , GeneratedCommandSpec "PURGE" (2) []
  , GeneratedCommandSpec "QUIT" (-1) []
  , GeneratedCommandSpec "RANDOMKEY" (1) []
  , GeneratedCommandSpec "READONLY" (1) []
  , GeneratedCommandSpec "READWRITE" (1) []
  , GeneratedCommandSpec "REFCOUNT" (3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "REMOVE" (3) []
  , GeneratedCommandSpec "RENAME" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "RENAMENX" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "REPLCONF" (-1) []
  , GeneratedCommandSpec "REPLICAOF" (3) []
  , GeneratedCommandSpec "REPLICAS" (3) []
  , GeneratedCommandSpec "REPLICAS" (3) []
  , GeneratedCommandSpec "REPLICATE" (3) []
  , GeneratedCommandSpec "REPLY" (3) []
  , GeneratedCommandSpec "RESET" (-2) []
  , GeneratedCommandSpec "RESET" (-2) []
  , GeneratedCommandSpec "RESET" (1) []
  , GeneratedCommandSpec "RESET" (3) []
  , GeneratedCommandSpec "RESET" (2) []
  , GeneratedCommandSpec "RESETSTAT" (2) []
  , GeneratedCommandSpec "RESTORE" (-3) []
  , GeneratedCommandSpec "RESTORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "RESTORE-ASKING" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "REWRITE" (2) []
  , GeneratedCommandSpec "ROLE" (1) []
  , GeneratedCommandSpec "RPOP" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "RPOPLPUSH" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "RPUSH" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "RPUSHX" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SADD" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SAVE" (2) []
  , GeneratedCommandSpec "SAVE" (1) []
  , GeneratedCommandSpec "SAVECONFIG" (2) []
  , GeneratedCommandSpec "SCAN" (-2) []
  , GeneratedCommandSpec "SCARD" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SCRIPT" (-2) []
  , GeneratedCommandSpec "SDIFF" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SDIFFSTORE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SELECT" (2) []
  , GeneratedCommandSpec "SENTINEL" (-2) []
  , GeneratedCommandSpec "SENTINELS" (3) []
  , GeneratedCommandSpec "SET" (-4) []
  , GeneratedCommandSpec "SET" (-5) []
  , GeneratedCommandSpec "SET" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SET-CONFIG-EPOCH" (3) []
  , GeneratedCommandSpec "SETBIT" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SETEX" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SETID" (-5) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SETINFO" (4) []
  , GeneratedCommandSpec "SETNAME" (3) []
  , GeneratedCommandSpec "SETNX" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SETRANGE" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SETSLOT" (-4) []
  , GeneratedCommandSpec "SETUSER" (-3) []
  , GeneratedCommandSpec "SHARDCHANNELS" (-2) []
  , GeneratedCommandSpec "SHARDNUMSUB" (-2) []
  , GeneratedCommandSpec "SHARDS" (2) []
  , GeneratedCommandSpec "SHUTDOWN" (-1) []
  , GeneratedCommandSpec "SIMULATE-FAILURE" (-3) []
  , GeneratedCommandSpec "SINTER" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SINTERCARD" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "SINTERSTORE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SISMEMBER" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SLAVEOF" (3) []
  , GeneratedCommandSpec "SLAVES" (3) []
  , GeneratedCommandSpec "SLAVES" (3) []
  , GeneratedCommandSpec "SLOTS" (2) []
  , GeneratedCommandSpec "SLOWLOG" (-2) []
  , GeneratedCommandSpec "SMEMBERS" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SMISMEMBER" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SMOVE" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SORT" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec BeginSearchUnsupported FindKeysUnsupported, GeneratedKeySpec BeginSearchUnsupported FindKeysUnsupported]
  , GeneratedCommandSpec "SORT_RO" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec BeginSearchUnsupported FindKeysUnsupported]
  , GeneratedCommandSpec "SPOP" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SPUBLISH" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SRANDMEMBER" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SREM" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SSCAN" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SSUBSCRIBE" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "STATS" (2) []
  , GeneratedCommandSpec "STATS" (2) []
  , GeneratedCommandSpec "STREAM" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "STRLEN" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SUBSCRIBE" (-2) []
  , GeneratedCommandSpec "SUBSTR" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "SUNION" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SUNIONSTORE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SUNSUBSCRIBE" (-1) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "SWAPDB" (3) []
  , GeneratedCommandSpec "SYNC" (1) []
  , GeneratedCommandSpec "TIME" (1) []
  , GeneratedCommandSpec "TOUCH" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "TRACKING" (-3) []
  , GeneratedCommandSpec "TRACKINGINFO" (2) []
  , GeneratedCommandSpec "TTL" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "TYPE" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "UNBLOCK" (-3) []
  , GeneratedCommandSpec "UNLINK" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "UNLOAD" (3) []
  , GeneratedCommandSpec "UNPAUSE" (2) []
  , GeneratedCommandSpec "UNSUBSCRIBE" (-1) []
  , GeneratedCommandSpec "UNWATCH" (1) []
  , GeneratedCommandSpec "USAGE" (-3) [GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "USERS" (2) []
  , GeneratedCommandSpec "WAIT" (3) []
  , GeneratedCommandSpec "WAITAOF" (4) []
  , GeneratedCommandSpec "WATCH" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (-1) (1) (0))]
  , GeneratedCommandSpec "WHOAMI" (2) []
  , GeneratedCommandSpec "XACK" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XADD" (-5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XAUTOCLAIM" (-6) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XCLAIM" (-6) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XDEL" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XGROUP" (-2) []
  , GeneratedCommandSpec "XINFO" (-2) []
  , GeneratedCommandSpec "XLEN" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XPENDING" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XRANGE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XREAD" (-4) [GeneratedKeySpec (BeginKeyword "STREAMS" (1)) (FindRange (-1) (1) (2))]
  , GeneratedCommandSpec "XREADGROUP" (-7) [GeneratedKeySpec (BeginKeyword "STREAMS" (4)) (FindRange (-1) (1) (2))]
  , GeneratedCommandSpec "XREVRANGE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XSETID" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "XTRIM" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZADD" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZCARD" (2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZCOUNT" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZDIFF" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZDIFFSTORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZINCRBY" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZINTER" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZINTERCARD" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZINTERSTORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZLEXCOUNT" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZMPOP" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZMSCORE" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZPOPMAX" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZPOPMIN" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANDMEMBER" (-2) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANGE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANGEBYLEX" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANGEBYSCORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANGESTORE" (-5) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZRANK" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREM" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREMRANGEBYLEX" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREMRANGEBYRANK" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREMRANGEBYSCORE" (4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREVRANGE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREVRANGEBYLEX" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREVRANGEBYSCORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZREVRANK" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZSCAN" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZSCORE" (3) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0))]
  , GeneratedCommandSpec "ZUNION" (-3) [GeneratedKeySpec (BeginIndex (1)) (FindKeyNum (0) (1) (1))]
  , GeneratedCommandSpec "ZUNIONSTORE" (-4) [GeneratedKeySpec (BeginIndex (1)) (FindRange (0) (1) (0)), GeneratedKeySpec (BeginIndex (2)) (FindKeyNum (0) (1) (1))]
  ]

generatedCommandSpecCount :: Int
generatedCommandSpecCount = 392
