save ""
appendonly no
bind 0.0.0.0

requirepass redis-client-e2e-password
masterauth redis-client-e2e-password
user redis-client-e2e-acl on >redis-client-e2e-acl-password ~* +@all

cluster-enabled yes
cluster-config-file nodes.conf
port 6379
cluster-announce-hostname redis-auth1.local
cluster-preferred-endpoint-type hostname
cluster-announce-port 6379
cluster-announce-bus-port 16379
