services:
  redis1:
    image: redis:7.2.12@sha256:16623900b6ddd58e8bac04ccb6b611b9a5d1aed165453e28bcaed251d549d62c
    container_name: redis-host-node1
    profiles: ["host-network"]
    network_mode: host
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis2:
    image: redis:7.2.12@sha256:16623900b6ddd58e8bac04ccb6b611b9a5d1aed165453e28bcaed251d549d62c
    container_name: redis-host-node2
    profiles: ["host-network"]
    network_mode: host
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis3:
    image: redis:7.2.12@sha256:16623900b6ddd58e8bac04ccb6b611b9a5d1aed165453e28bcaed251d549d62c
    container_name: redis-host-node3
    profiles: ["host-network"]
    network_mode: host
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis4:
    image: redis:7.2.12@sha256:16623900b6ddd58e8bac04ccb6b611b9a5d1aed165453e28bcaed251d549d62c
    container_name: redis-host-node4
    profiles: ["host-network"]
    network_mode: host
    volumes:
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis5:
    image: redis:7.2.12@sha256:16623900b6ddd58e8bac04ccb6b611b9a5d1aed165453e28bcaed251d549d62c
    container_name: redis-host-node5
    profiles: ["host-network"]
    network_mode: host
    volumes:
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
